spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
        
    mail:
        properties:
            mail:
                host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
                username: ${MAIL_USERNAME}
                password: ${MAIL_PASSWORD}
                smtp:
                    port: 2525
                    auth: true
                    starttls:
                        enabled: true
                        required: true
                transport:
                    protocol: smtp
    
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
    